export const PRODUCT_MEASUREMENT_UNITS = {
  UNIT: 'unit',
  KG: 'kg',
  G: 'g',
  L: 'l',
  ML: 'ml',
  PACK: 'pack',
  BOX: 'box',
};

export const PRODUCT_MEASUREMENT_UNIT_VALUES = Object.values(PRODUCT_MEASUREMENT_UNITS);

export const DEFAULT_PRODUCT_MEASUREMENT_UNIT = PRODUCT_MEASUREMENT_UNITS.UNIT;

export const PRODUCT_MEASUREMENT_UNIT_LABELS = {
  [PRODUCT_MEASUREMENT_UNITS.UNIT]: 'Unidade',
  [PRODUCT_MEASUREMENT_UNITS.KG]: 'Kg',
  [PRODUCT_MEASUREMENT_UNITS.G]: 'Grama',
  [PRODUCT_MEASUREMENT_UNITS.L]: 'Litro',
  [PRODUCT_MEASUREMENT_UNITS.ML]: 'ml',
  [PRODUCT_MEASUREMENT_UNITS.PACK]: 'Pacote',
  [PRODUCT_MEASUREMENT_UNITS.BOX]: 'Caixa',
};

export const FRACTIONAL_PRODUCT_MEASUREMENT_UNIT_VALUES = [
  PRODUCT_MEASUREMENT_UNITS.KG,
  PRODUCT_MEASUREMENT_UNITS.G,
  PRODUCT_MEASUREMENT_UNITS.L,
  PRODUCT_MEASUREMENT_UNITS.ML,
];

export const INTEGER_PRODUCT_MEASUREMENT_UNIT_VALUES = [
  PRODUCT_MEASUREMENT_UNITS.UNIT,
  PRODUCT_MEASUREMENT_UNITS.PACK,
  PRODUCT_MEASUREMENT_UNITS.BOX,
];
