export function getDemoSiteFallback() {
  return {
    business: {
      id: 'demo-business-1',
      slug: 'barbearia-estilo-vivo',
      name: 'Barbearia Estilo Vivo',
      legalName: 'Barbearia Estilo Vivo LTDA',
      description:
        'Barbearia tradicional com profissionais experientes, oferecendo servicos de corte, barba e relaxamento capilar com qualidade premium.',
      logoUrl:
        'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=320&q=80',
      bannerUrl:
        'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1600&q=80',
      badge: 'Barbearia Estilo Vivo',
      status: 'active',
      address: {
        display: 'Av. Paulista, 1000 - Bela Vista, Sao Paulo - SP',
        mapUrl:
          'https://www.google.com/maps/search/?api=1&query=Av.+Paulista,+1000+-+Bela+Vista,+S%C3%A3o+Paulo+-+SP',
      },
      hours: [
        { id: 'weekday', label: 'Terca a Sexta', value: '10:00 - 20:00' },
        { id: 'saturday', label: 'Sabado', value: '09:00 - 17:00' },
        { id: 'sunday', label: 'Domingo', value: 'Fechado' },
      ],
      rating: '4.8/5.0',
      contact: {
        whatsapp: '5511998765432',
        phone: '5511998765432',
        email: 'contato@barbearia.com',
        wifi: {
          ssid: 'Barbearia-WiFi',
          password: 'Barbearia123',
          security: 'WPA',
          title: 'Wi-Fi da Barbearia',
          description: 'Use a senha abaixo para se conectar ao Wi-Fi de cortesia enquanto espera.',
        },
        pix: {
          keyType: 'cpf',
          key: '12345678900',
          receiverName: 'Barbearia Estilo Vivo',
          city: 'Sao Paulo',
          description: 'Escaneie o QR Code ou copie a chave PIX para pagar instantaneamente.',
          actionLabel: 'Chave PIX CPF',
          actionDescription: '12345678900',
        },
      },
      seo: {
        title: 'Barbearia Estilo Vivo | Pagina NFC',
        description:
          'Pagina NFC da Barbearia Estilo Vivo com links rapidos, servicos, PIX, Wi-Fi e informacoes do negocio.',
        imageUrl:
          'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1200&q=80',
      },
    },
    theme: {
      colors: {
        primary: '#f97316',
        secondary: '#fb7185',
        background: '#140d09',
        surface: 'rgba(31, 20, 16, 0.92)',
        surfaceAlt: 'rgba(48, 32, 24, 0.86)',
        text: '#fff8f2',
        textMuted: '#f4d5c3',
        border: 'rgba(255, 255, 255, 0.12)',
        success: '#22c55e',
        danger: '#ef4444',
        accent: 'rgba(249, 115, 22, 0.18)',
      },
      typography: {
        headingFamily: "'Space Grotesk', sans-serif",
        bodyFamily: "'Manrope', sans-serif",
        baseSize: '16px',
        heroSize: 'clamp(2.2rem, 5.8vw, 4rem)',
        sectionTitleSize: 'clamp(1.15rem, 2.8vw, 1.7rem)',
      },
      spacing: {
        xs: '0.35rem',
        sm: '0.65rem',
        md: '1rem',
        lg: '1.4rem',
        xl: '1.8rem',
        xxl: '2.4rem',
      },
      radius: {
        sm: '0.9rem',
        md: '1.4rem',
        lg: '2rem',
        pill: '999px',
      },
      layout: {
        maxWidth: '1180px',
        pagePadding: 'clamp(1rem, 3vw, 2rem)',
        sectionGap: '1.1rem',
        cardGap: '0.85rem',
      },
      buttons: {
        primary: {
          background: 'linear-gradient(135deg, #f97316, #fb7185)',
          color: '#ffffff',
          border: 'none',
        },
        secondary: {
          background: 'rgba(255, 255, 255, 0.06)',
          color: '#fff8f2',
          border: '1px solid rgba(255, 255, 255, 0.12)',
        },
      },
      customCss: '',
    },
    sections: [
      {
        id: 'hero-main',
        key: 'hero-main',
        type: 'hero',
        title: 'Barbearia Estilo Vivo',
        description:
          'Visual premium, atendimento agil e todos os atalhos da barbearia em uma pagina NFC dinamica.',
        order: 10,
        visible: true,
        variant: 'spotlight',
        settings: {
          badge: 'Landing Page NFC',
          showAddress: true,
          showHours: true,
          showRating: true,
          rating: '4.8/5.0',
          address: 'Av. Paulista, 1000 - Bela Vista, Sao Paulo - SP',
          hours: [
            { id: 'weekday', label: 'Terca a Sexta', value: '10:00 - 20:00' },
            { id: 'saturday', label: 'Sabado', value: '09:00 - 17:00' },
            { id: 'sunday', label: 'Domingo', value: 'Fechado' },
          ],
          bannerUrl:
            'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1600&q=80',
          primaryAction: {
            label: 'Agendar pelo WhatsApp',
            href: 'https://wa.me/5511998765432',
          },
          secondaryAction: {
            label: 'Copiar PIX',
            action: 'pix',
          },
        },
        items: [],
      },
      {
        id: 'quick-actions',
        key: 'quick-actions',
        type: 'links',
        title: 'Acesso rapido',
        description: 'Concentre atendimento, localizacao, pagamento e conveniencias nos botoes abaixo.',
        order: 20,
        visible: true,
        settings: {
          group: 'primary',
          layout: 'compact',
        },
        items: [
          {
            id: 'link-whatsapp',
            type: 'contact',
            group: 'primary',
            label: 'Enviar mensagem',
            subtitle: 'Resposta rapida no WhatsApp',
            icon: 'whatsapp',
            url: 'https://wa.me/5511998765432',
            order: 1,
            target: '_blank',
            metadata: {},
          },
          {
            id: 'link-phone',
            type: 'contact',
            group: 'primary',
            label: 'Ligar agora',
            subtitle: 'Fale com a recepcao',
            icon: 'phone',
            url: 'tel:+5511998765432',
            order: 2,
            target: '_self',
            metadata: {},
          },
          {
            id: 'link-location',
            type: 'external',
            group: 'primary',
            label: 'Como chegar',
            subtitle: 'Abra a rota no mapa',
            icon: 'map',
            url: 'https://www.google.com/maps/search/?api=1&query=Av.+Paulista,+1000+-+Bela+Vista,+S%C3%A3o+Paulo+-+SP',
            order: 3,
            target: '_blank',
            metadata: {},
          },
          {
            id: 'link-wifi',
            type: 'wifi',
            group: 'primary',
            label: 'Abrir Wi-Fi',
            subtitle: 'Senha e QR Code em pop-up',
            icon: 'wifi',
            value: 'Barbearia123',
            order: 4,
            target: '_self',
            metadata: { action: 'wifi' },
          },
          {
            id: 'link-pix',
            type: 'pix',
            group: 'primary',
            label: 'Copiar PIX',
            subtitle: 'Copie a chave PIX em um toque',
            icon: 'pix',
            value: '12345678900',
            order: 5,
            target: '_self',
            metadata: { action: 'pix' },
          },
          {
            id: 'link-instagram',
            type: 'social',
            group: 'primary',
            label: 'Instagram',
            subtitle: 'Fotos, novidades e destaques',
            icon: 'instagram',
            url: 'https://instagram.com/barbearia.estilovivo',
            order: 6,
            target: '_blank',
            metadata: {},
          },
        ],
      },
      {
        id: 'services',
        key: 'services',
        type: 'services',
        title: 'Nossos servicos',
        description: 'Catalogo rapido para o cliente entender precos e ja iniciar o pagamento ou contato.',
        order: 30,
        visible: true,
        settings: {
          showPixShortcut: true,
        },
        items: [
          {
            id: 'service-1',
            name: 'Corte masculino',
            description: 'Corte classico com navalha ou maquina',
            price: 45,
            ctaLabel: 'Gerar QR PIX',
          },
          {
            id: 'service-2',
            name: 'Barba e acabamento',
            description: 'Aparacao e design da barba',
            price: 35,
            ctaLabel: 'Gerar QR PIX',
          },
          {
            id: 'service-3',
            name: 'Combo corte + barba',
            description: 'Corte completo com acabamento de barba',
            price: 75,
            ctaLabel: 'Gerar QR PIX',
          },
          {
            id: 'service-4',
            name: 'Relaxamento capilar',
            description: 'Tratamento capilar premium com alisamento',
            price: 120,
            ctaLabel: 'Gerar QR PIX',
          },
        ],
      },
      {
        id: 'contact',
        key: 'contact',
        type: 'contact',
        title: 'Contato e atendimento',
        description: 'Horarios, endereco e canais para falar com a equipe sem precisar sair da pagina.',
        order: 40,
        visible: true,
        settings: {
          hours: [
            { id: 'weekday', label: 'Terca a Sexta', value: '10:00 - 20:00' },
            { id: 'saturday', label: 'Sabado', value: '09:00 - 17:00' },
            { id: 'sunday', label: 'Domingo', value: 'Fechado' },
          ],
        },
        items: [
          {
            id: 'contact-whatsapp',
            label: 'WhatsApp',
            value: '5511998765432',
            href: 'https://wa.me/5511998765432',
          },
          {
            id: 'contact-phone',
            label: 'Telefone',
            value: '5511998765432',
            href: 'tel:+5511998765432',
          },
          {
            id: 'contact-email',
            label: 'E-mail',
            value: 'contato@barbearia.com',
            href: 'mailto:contato@barbearia.com',
          },
          {
            id: 'contact-address',
            label: 'Endereco',
            value: 'Av. Paulista, 1000 - Bela Vista, Sao Paulo - SP',
            href: 'https://www.google.com/maps/search/?api=1&query=Av.+Paulista,+1000+-+Bela+Vista,+S%C3%A3o+Paulo+-+SP',
          },
        ],
      },
      {
        id: 'gallery',
        key: 'gallery',
        type: 'gallery',
        title: 'Galeria de ambientes e cortes',
        description: 'Veja detalhes do ambiente e da experiencia que o cliente encontra ao aproximar a tag.',
        order: 50,
        visible: true,
        settings: {},
        items: [
          {
            id: 'gallery-1',
            imageUrl:
              'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
            alt: 'Corte de cabelo masculino moderno',
          },
          {
            id: 'gallery-2',
            imageUrl:
              'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
            alt: 'Profissional barbeiro em acao',
          },
          {
            id: 'gallery-3',
            imageUrl:
              'https://images.unsplash.com/photo-1551478734-6a6d2356a8a2?auto=format&fit=crop&w=1200&q=80',
            alt: 'Interior da barbearia com otima estrutura',
          },
        ],
      },
      {
        id: 'about',
        key: 'about',
        type: 'custom',
        title: 'Sobre nos',
        description:
          'Barbearia tradicional com profissionais experientes, oferecendo servicos de corte, barba e relaxamento capilar com qualidade premium.',
        order: 60,
        visible: true,
        settings: {
          tone: 'story',
          eyebrow: 'Experiencia local',
        },
        items: [
          {
            id: 'about-paragraph-1',
            body: 'Nossa pagina NFC funciona como um mini hub do negocio: atendimento, pagamentos e informacoes importantes em um unico lugar.',
          },
        ],
      },
      {
        id: 'wifi',
        key: 'wifi',
        type: 'wifi',
        title: 'Wi-Fi da Barbearia',
        description: 'Use a senha abaixo para se conectar ao nosso Wi-Fi de cortesia.',
        order: 70,
        visible: true,
        settings: {
          displayMode: 'modal',
          ssid: 'Barbearia-WiFi',
          password: 'Barbearia123',
          security: 'WPA',
          qrDescription: 'Mostre este QR Code para conectar automaticamente a rede.',
        },
        items: [],
      },
      {
        id: 'pix',
        key: 'pix',
        type: 'pix',
        title: 'Pagamento via PIX',
        description: 'Escaneie o QR Code ou copie a chave PIX abaixo.',
        order: 80,
        visible: true,
        settings: {
          keyType: 'cpf',
          key: '12345678900',
          receiverName: 'Barbearia Estilo Vivo',
          city: 'Sao Paulo',
          description: 'Escaneie o QR Code ou copie a chave PIX para pagar instantaneamente.',
          actionLabel: 'Chave PIX CPF',
          actionDescription: '12345678900',
          allowAmountInput: true,
        },
        items: [],
      },
      {
        id: 'social',
        key: 'social',
        type: 'social',
        title: 'Redes e canais digitais',
        description: 'Continue o relacionamento com o negocio mesmo fora da visita presencial.',
        order: 90,
        visible: false,
        settings: {
          group: 'social',
        },
        items: [
          {
            id: 'social-instagram',
            type: 'social',
            label: 'Instagram',
            subtitle: '@barbearia.estilovivo',
            url: 'https://instagram.com/barbearia.estilovivo',
            target: '_blank',
          },
          {
            id: 'social-email',
            type: 'contact',
            label: 'E-mail',
            subtitle: 'contato@barbearia.com',
            url: 'mailto:contato@barbearia.com',
            target: '_self',
          },
        ],
      },
      {
        id: 'cta',
        key: 'cta',
        type: 'cta',
        title: 'Pronto para voltar?',
        description: 'Salve a pagina NFC da barbearia e compartilhe com quem gosta de atendimento premium.',
        order: 100,
        visible: true,
        settings: {
          primaryAction: {
            label: 'Enviar mensagem',
            href: 'https://wa.me/5511998765432',
          },
          secondaryAction: {
            label: 'Ver Instagram',
            href: 'https://instagram.com/barbearia.estilovivo',
          },
        },
        items: [],
      },
    ],
    links: [],
    seo: {
      title: 'Barbearia Estilo Vivo | Pagina NFC',
      description:
        'Pagina NFC da Barbearia Estilo Vivo com links rapidos, servicos, PIX, Wi-Fi e informacoes do negocio.',
      imageUrl:
        'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1200&q=80',
    },
  };
}
