import { LINK_GROUPS, LINK_TYPES, PLAN_TYPES, SECTION_TYPES } from '../../../shared/constants/index.js';

export function getLegacyDemoSeed() {
  return {
    business: {
      name: 'Barbearia Estilo Vivo',
      slug: 'barbearia-estilo-vivo',
      description:
        'Barbearia tradicional com profissionais experientes, oferecendo servicos de corte, barba e relaxamento capilar com qualidade premium.',
      logoUrl:
        'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=320&q=80',
      bannerUrl:
        'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1600&q=80',
      badge: 'Barbearia Estilo Vivo',
      status: 'active',
      rating: '4.8/5.0',
      address: {
        display: 'Av. Paulista, 1000 - Bela Vista, Sao Paulo - SP',
        mapUrl:
          'https://www.google.com/maps/search/?api=1&query=Av.+Paulista,+1000+-+Bela+Vista,+S%C3%A3o+Paulo+-+SP',
      },
      hours: [
        { id: 'weekday', label: 'Terca a Sexta', value: '10:00 - 20:00' },
        { id: 'saturday', label: 'Sabado', value: '09:00 - 17:00' },
        { id: 'sunday', label: 'Domingo', value: 'Fechado' },
      ],
      contact: {
        whatsapp: '5511998765432',
        phone: '5511998765432',
        email: 'contato@barbearia.com',
        wifi: {
          ssid: 'Barbearia-WiFi',
          password: 'Barbearia123',
          security: 'WPA',
          title: 'Wi-Fi da Barbearia',
          description: 'Use a senha abaixo para se conectar ao Wi-Fi de cortesia enquanto espera.',
        },
        pix: {
          keyType: 'cpf',
          key: '12345678900',
          receiverName: 'Barbearia Estilo Vivo',
          city: 'Sao Paulo',
          description: 'Escaneie o QR Code ou copie a chave PIX para pagar instantaneamente.',
          actionLabel: 'Chave PIX CPF',
          actionDescription: '12345678900',
        },
      },
      seo: {
        title: 'Barbearia Estilo Vivo | Pagina NFC',
        description:
          'Pagina NFC da Barbearia Estilo Vivo com links rapidos, servicos, PIX, Wi-Fi e informacoes do negocio.',
        imageUrl:
          'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1200&q=80',
      },
    },
    theme: {
      colors: {
        primary: '#f97316',
        secondary: '#fb7185',
        background: '#140d09',
        surface: 'rgba(31, 20, 16, 0.92)',
        surfaceAlt: 'rgba(48, 32, 24, 0.86)',
        text: '#fff8f2',
        textMuted: '#f4d5c3',
        border: 'rgba(255, 255, 255, 0.12)',
        success: '#22c55e',
        danger: '#ef4444',
        accent: 'rgba(249, 115, 22, 0.18)',
      },
      typography: {
        headingFamily: "'Space Grotesk', sans-serif",
        bodyFamily: "'Manrope', sans-serif",
        baseSize: '16px',
        heroSize: 'clamp(2.2rem, 5.8vw, 4rem)',
        sectionTitleSize: 'clamp(1.15rem, 2.8vw, 1.7rem)',
      },
      spacing: {
        xs: '0.35rem',
        sm: '0.65rem',
        md: '1rem',
        lg: '1.4rem',
        xl: '1.8rem',
        xxl: '2.4rem',
      },
      radius: {
        sm: '0.9rem',
        md: '1.4rem',
        lg: '2rem',
        pill: '999px',
      },
      layout: {
        maxWidth: '1180px',
        pagePadding: 'clamp(1rem, 3vw, 2rem)',
        sectionGap: '1.1rem',
        cardGap: '0.85rem',
      },
      buttons: {
        primary: {
          background: 'linear-gradient(135deg, #f97316, #fb7185)',
          color: '#ffffff',
          border: 'none',
        },
        secondary: {
          background: 'rgba(255, 255, 255, 0.06)',
          color: '#fff8f2',
          border: '1px solid rgba(255, 255, 255, 0.12)',
        },
      },
      customCss: '',
    },
    links: [
      {
        type: LINK_TYPES.CONTACT,
        group: LINK_GROUPS.PRIMARY,
        label: 'Enviar mensagem',
        subtitle: 'Resposta rapida no WhatsApp',
        icon: 'whatsapp',
        url: 'https://wa.me/5511998765432',
        order: 1,
        target: '_blank',
        metadata: { action: 'whatsapp' },
      },
      {
        type: LINK_TYPES.CONTACT,
        group: LINK_GROUPS.PRIMARY,
        label: 'Ligar agora',
        subtitle: 'Fale com a recepcao',
        icon: 'phone',
        url: 'tel:+5511998765432',
        order: 2,
        target: '_self',
        metadata: { action: 'phone' },
      },
      {
        type: LINK_TYPES.CONTACT,
        group: LINK_GROUPS.PRIMARY,
        label: 'E-mail',
        subtitle: 'Envie uma mensagem',
        icon: 'mail',
        url: 'mailto:contato@barbearia.com',
        order: 3,
        target: '_self',
        metadata: { action: 'email' },
      },
      {
        type: LINK_TYPES.WIFI,
        group: LINK_GROUPS.PRIMARY,
        label: 'Abrir Wi-Fi',
        subtitle: 'Senha e QR Code em pop-up',
        icon: 'wifi',
        value: 'Barbearia123',
        order: 4,
        target: '_self',
        metadata: { action: 'wifi' },
      },
      {
        type: LINK_TYPES.PIX,
        group: LINK_GROUPS.PRIMARY,
        label: 'Copiar PIX',
        subtitle: 'Copie a chave PIX em um toque',
        icon: 'pix',
        value: '12345678900',
        order: 5,
        target: '_self',
        metadata: { action: 'pix' },
      },
      {
        type: LINK_TYPES.SOCIAL,
        group: LINK_GROUPS.PRIMARY,
        label: 'Instagram',
        subtitle: 'Fotos, novidades e destaques',
        icon: 'instagram',
        url: 'https://instagram.com/barbearia.estilovivo',
        order: 6,
        target: '_blank',
      },
      {
        type: LINK_TYPES.SOCIAL,
        group: LINK_GROUPS.SOCIAL,
        label: 'Instagram',
        subtitle: '@barbearia.estilovivo',
        icon: 'instagram',
        url: 'https://instagram.com/barbearia.estilovivo',
        order: 7,
        target: '_blank',
      },
    ],
    sections: [
      {
        key: 'hero-main',
        type: SECTION_TYPES.HERO,
        title: 'Barbearia Estilo Vivo',
        description: 'Visual premium, atendimento agil e todos os atalhos da barbearia em uma pagina NFC dinamica.',
        order: 10,
        visible: true,
        variant: 'spotlight',
        settings: {
          badge: 'Landing Page NFC',
          showAddress: true,
          showHours: true,
          showRating: true,
          primaryAction: {
            label: 'Agendar pelo WhatsApp',
            href: 'https://wa.me/5511998765432',
          },
          secondaryAction: {
            label: 'Copiar PIX',
            action: 'pix',
          },
        },
        items: [],
      },
      {
        key: 'quick-actions',
        type: SECTION_TYPES.LINKS,
        title: 'Acesso rapido',
        description: 'Concentre atendimento, localizacao, pagamento e conveniencias nos botoes abaixo.',
        order: 20,
        visible: true,
        settings: {
          group: LINK_GROUPS.PRIMARY,
          layout: 'compact',
        },
        items: [],
      },
      {
        key: 'services',
        type: SECTION_TYPES.SERVICES,
        title: 'Nossos servicos',
        description: 'Catalogo rapido para o cliente entender precos e ja iniciar o pagamento ou contato.',
        order: 30,
        visible: true,
        settings: {
          showPixShortcut: true,
        },
        items: [
          {
            id: 'service-1',
            name: 'Corte masculino',
            description: 'Corte classico com navalha ou maquina',
            price: 45,
            ctaLabel: 'Gerar QR PIX',
          },
          {
            id: 'service-2',
            name: 'Barba e acabamento',
            description: 'Aparacao e design da barba',
            price: 35,
            ctaLabel: 'Gerar QR PIX',
          },
          {
            id: 'service-3',
            name: 'Combo corte + barba',
            description: 'Corte completo com acabamento de barba',
            price: 75,
            ctaLabel: 'Gerar QR PIX',
          },
          {
            id: 'service-4',
            name: 'Relaxamento capilar',
            description: 'Tratamento capilar premium com alisamento',
            price: 120,
            ctaLabel: 'Gerar QR PIX',
          },
        ],
      },
      {
        key: 'contact',
        type: SECTION_TYPES.CONTACT,
        title: 'Contato e atendimento',
        description: 'Horarios, endereco e canais para falar com a equipe sem precisar sair da pagina.',
        order: 40,
        visible: true,
        settings: {},
        items: [],
      },
      {
        key: 'gallery',
        type: SECTION_TYPES.GALLERY,
        title: 'Galeria de ambientes e cortes',
        description: 'Veja detalhes do ambiente e da experiencia que o cliente encontra ao aproximar a tag.',
        order: 50,
        visible: true,
        settings: {},
        items: [
          {
            id: 'gallery-1',
            imageUrl:
              'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
            alt: 'Corte de cabelo masculino moderno',
          },
          {
            id: 'gallery-2',
            imageUrl:
              'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
            alt: 'Profissional barbeiro em acao',
          },
          {
            id: 'gallery-3',
            imageUrl:
              'https://images.unsplash.com/photo-1551478734-6a6d2356a8a2?auto=format&fit=crop&w=1200&q=80',
            alt: 'Interior da barbearia com otima estrutura',
          },
        ],
      },
      {
        key: 'about',
        type: SECTION_TYPES.CUSTOM,
        title: 'Sobre nos',
        description: '',
        order: 60,
        visible: true,
        settings: {
          tone: 'story',
          eyebrow: 'Experiencia local',
        },
        items: [
          {
            id: 'about-paragraph-1',
            body: 'Nossa pagina NFC funciona como um mini hub do negocio: atendimento, pagamentos e informacoes importantes em um unico lugar.',
          },
        ],
      },
      {
        key: 'wifi',
        type: SECTION_TYPES.WIFI,
        title: 'Wi-Fi da Barbearia',
        description: 'Use a senha abaixo para se conectar ao nosso Wi-Fi de cortesia.',
        order: 70,
        visible: true,
        settings: {
          displayMode: 'modal',
          qrDescription: 'Mostre este QR Code para conectar automaticamente a rede.',
        },
        items: [],
      },
      {
        key: 'pix',
        type: SECTION_TYPES.PIX,
        title: 'Pagamento via PIX',
        description: 'Escaneie o QR Code ou copie a chave PIX abaixo.',
        order: 80,
        visible: true,
        settings: {
          allowAmountInput: true,
        },
        items: [],
      },
      {
        key: 'social',
        type: SECTION_TYPES.SOCIAL,
        title: 'Redes e canais digitais',
        description: 'Continue o relacionamento com o negocio mesmo fora da visita presencial.',
        order: 90,
        visible: false,
        settings: {
          group: LINK_GROUPS.SOCIAL,
        },
        items: [],
      },
      {
        key: 'cta',
        type: SECTION_TYPES.CTA,
        title: '',
        description: '',
        order: 100,
        visible: false,
        settings: {},
        items: [],
      },
    ],
    nfcTag: {
      code: 'NFC-BARB-001',
      status: 'active',
    },
    plan: {
      code: 'free-demo',
      name: 'Plano Free Demo',
      type: PLAN_TYPES.FREE,
      priceCents: 0,
      currency: 'BRL',
      features: ['Pagina publica por slug', 'Tema configuravel', 'Analytics basico'],
    },
  };
}
